version: '3.2'

services:
  db:
    image: postgres:11.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  app:
    image: spread-it-api:latest
    build: .
    ports:
      - '3000:3000'
      - '5500:5500'
    depends_on:
      - db
    command: ['npm', 'run', 'start']
